-- MySQL Script generated by MySQL Workbench
-- Fri Feb 17 22:44:53 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`liebie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`liebie` (
  `idliebie` INT NOT NULL,
  `lb_name` VARCHAR(45) NULL,
  PRIMARY KEY (`idliebie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`exam`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`exam` (
  `ex_code` VARCHAR(45) NULL,
  `ex_name` VARCHAR(45) NOT NULL,
  `ex_date` DATE NULL,
  `ex_document` VARCHAR(100) NULL,
  `ex_leibie` VARCHAR(45) NULL,
  `liebie_idliebie` INT NOT NULL,
  PRIMARY KEY (`ex_name`, `liebie_idliebie`),
  INDEX `fk_exam_liebie1_idx` (`liebie_idliebie` ASC),
  CONSTRAINT `fk_exam_liebie1`
    FOREIGN KEY (`liebie_idliebie`)
    REFERENCES `mydb`.`liebie` (`idliebie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`kemu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`kemu` (
  `km_name` VARCHAR(45) NOT NULL,
  `km_rs` INT NULL,
  `km_sj_count` INT NULL,
  `km_start_time` DATETIME NULL,
  `ks_end_time` DATETIME NULL,
  `km_level` VARCHAR(45) NULL,
  `km_hegefenshu` FLOAT NULL,
  `ex_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`km_name`, `ex_name`),
  INDEX `fk_kemu_exam_idx` (`ex_name` ASC),
  CONSTRAINT `fk_kemu_exam`
    FOREIGN KEY (`ex_name`)
    REFERENCES `mydb`.`exam` (`ex_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ksinfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ksinfo` (
  `ks_idcard` CHAR(18) NOT NULL,
  `ks_name` VARCHAR(45) NULL,
  `ks_age` INT NULL,
  `ks_sex` CHAR(5) NULL,
  `ks_phonenum` CHAR(11) NULL,
  `ks_danwei` VARCHAR(45) NULL,
  `ks_jiguan` VARCHAR(45) NULL,
  `ks_xueli` VARCHAR(45) NULL,
  `ks_school` VARCHAR(45) NULL,
  `ks_biyedate` DATE NULL,
  PRIMARY KEY (`ks_idcard`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`zhaokaodanwei`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`zhaokaodanwei` (
  `dw_id` INT NOT NULL,
  `dw_name` VARCHAR(45) NULL,
  `dw_phonenum` VARCHAR(11) NULL,
  `ex_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`dw_id`, `ex_name`),
  INDEX `fk_zhaokaodanwei_exam1_idx` (`ex_name` ASC),
  CONSTRAINT `fk_zhaokaodanwei_exam1`
    FOREIGN KEY (`ex_name`)
    REFERENCES `mydb`.`exam` (`ex_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`zhiwei`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`zhiwei` (
  `zw_code` VARCHAR(12) NOT NULL,
  `zw_name` VARCHAR(45) NULL,
  `zw_zhaokaors` INT NULL,
  `zw_tiaojian` VARCHAR(45) NULL,
  `zw_document` VARCHAR(45) NULL,
  `zhaokaodanwei_dw_id` INT NOT NULL,
  `zhaokaodanwei_exam_ex_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`zw_code`, `zhaokaodanwei_dw_id`, `zhaokaodanwei_exam_ex_name`),
  INDEX `fk_zhiwei_zhaokaodanwei1_idx` (`zhaokaodanwei_dw_id` ASC, `zhaokaodanwei_exam_ex_name` ASC),
  CONSTRAINT `fk_zhiwei_zhaokaodanwei1`
    FOREIGN KEY (`zhaokaodanwei_dw_id` , `zhaokaodanwei_exam_ex_name`)
    REFERENCES `mydb`.`zhaokaodanwei` (`dw_id` , `ex_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`kaodian`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`kaodian` (
  `idkaodian` INT NULL,
  `kd_name` VARCHAR(45) NOT NULL,
  `kd_jscount` INT NULL,
  `kd_manager` VARCHAR(45) NULL,
  `kd_phonenum` CHAR(11) NULL,
  `kd_address` VARCHAR(45) NULL,
  `kd_pby_count` INT NULL,
  `kd_smy_count` INT NULL,
  PRIMARY KEY (`kd_name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`exam_has_kaodian`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`exam_has_kaodian` (
  `ex_name` VARCHAR(45) NOT NULL,
  `kd_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ex_name`, `kd_name`),
  INDEX `fk_exam_has_kaodian_kaodian1_idx` (`kd_name` ASC),
  INDEX `fk_exam_has_kaodian_exam1_idx` (`ex_name` ASC),
  CONSTRAINT `fk_exam_has_kaodian_exam1`
    FOREIGN KEY (`ex_name`)
    REFERENCES `mydb`.`exam` (`ex_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exam_has_kaodian_kaodian1`
    FOREIGN KEY (`kd_name`)
    REFERENCES `mydb`.`kaodian` (`kd_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`jiaoshi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`jiaoshi` (
  `idjiaoshi` INT NOT NULL,
  `js_iner_index` INT NULL,
  `js_banjiname` VARCHAR(45) NULL,
  `zkz_start` BIGINT NULL,
  `zkz_end` BIGINT NULL,
  `ex_name` VARCHAR(45) NULL,
  `kd_name` VARCHAR(45) NULL,
  PRIMARY KEY (`idjiaoshi`),
  INDEX `fk_jiaoshi_exam_has_kaodian1_idx` (`ex_name` ASC, `kd_name` ASC),
  CONSTRAINT `fk_jiaoshi_exam_has_kaodian1`
    FOREIGN KEY (`ex_name` , `kd_name`)
    REFERENCES `mydb`.`exam_has_kaodian` (`ex_name` , `kd_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`kaochang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`kaochang` (
  `idkaochang` INT NOT NULL,
  `kc_renshu` INT NULL,
  `km_name` VARCHAR(45) NULL,
  `ex_name` VARCHAR(45) NULL,
  `idjiaoshi` INT NULL,
  PRIMARY KEY (`idkaochang`),
  INDEX `fk_kaochang_kemu1_idx` (`km_name` ASC, `ex_name` ASC),
  INDEX `fk_kaochang_jiaoshi1_idx` (`idjiaoshi` ASC),
  CONSTRAINT `fk_kaochang_kemu1`
    FOREIGN KEY (`km_name` , `ex_name`)
    REFERENCES `mydb`.`kemu` (`km_name` , `ex_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_kaochang_jiaoshi1`
    FOREIGN KEY (`idjiaoshi`)
    REFERENCES `mydb`.`jiaoshi` (`idjiaoshi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`kaodianrenyuan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`kaodianrenyuan` (
  `kdry_name` VARCHAR(45) NOT NULL,
  `kdry_role` VARCHAR(45) NULL,
  `kdry_phonenum` VARCHAR(45) NULL,
  `kaodian_kd_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`kdry_name`, `kaodian_kd_name`),
  INDEX `fk_kaodianrenyuan_kaodian1_idx` (`kaodian_kd_name` ASC),
  CONSTRAINT `fk_kaodianrenyuan_kaodian1`
    FOREIGN KEY (`kaodian_kd_name`)
    REFERENCES `mydb`.`kaodian` (`kd_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`jiashiyuan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`jiashiyuan` (
  `jsy_name` VARCHAR(20) NOT NULL,
  `jsy_chepai` VARCHAR(45) NULL,
  `jsy_phonenum` VARCHAR(11) NULL,
  `kaodian_kd_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`jsy_name`, `kaodian_kd_name`),
  INDEX `fk_jiashiyuan_kaodian1_idx` (`kaodian_kd_name` ASC),
  CONSTRAINT `fk_jiashiyuan_kaodian1`
    FOREIGN KEY (`kaodian_kd_name`)
    REFERENCES `mydb`.`kaodian` (`kd_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ksinfo_has_kemu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ksinfo_has_kemu` (
  `ksinfo_ks_idcard` CHAR(18) NOT NULL,
  `km_name` VARCHAR(45) NOT NULL,
  `ex_name` VARCHAR(45) NOT NULL,
  `idkaochang` INT NULL,
  PRIMARY KEY (`ksinfo_ks_idcard`, `ex_name`, `km_name`),
  INDEX `fk_ksinfo_has_kemu_kemu1_idx` (`km_name` ASC, `ex_name` ASC),
  INDEX `fk_ksinfo_has_kemu_ksinfo1_idx` (`ksinfo_ks_idcard` ASC),
  INDEX `fk_ksinfo_has_kemu_kaochang1_idx` (`idkaochang` ASC),
  CONSTRAINT `fk_ksinfo_has_kemu_ksinfo1`
    FOREIGN KEY (`ksinfo_ks_idcard`)
    REFERENCES `mydb`.`ksinfo` (`ks_idcard`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ksinfo_has_kemu_kemu1`
    FOREIGN KEY (`km_name` , `ex_name`)
    REFERENCES `mydb`.`kemu` (`km_name` , `ex_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ksinfo_has_kemu_kaochang1`
    FOREIGN KEY (`idkaochang`)
    REFERENCES `mydb`.`kaochang` (`idkaochang`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ksinfo_has_zhiwei`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ksinfo_has_zhiwei` (
  `ksinfo_ks_idcard` CHAR(18) NOT NULL,
  `zhiwei_zw_code` VARCHAR(12) NOT NULL,
  `dw_id` INT NOT NULL,
  `ex_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ksinfo_ks_idcard`, `ex_name`, `zhiwei_zw_code`, `dw_id`),
  INDEX `fk_ksinfo_has_zhiwei_zhiwei1_idx` (`zhiwei_zw_code` ASC, `dw_id` ASC, `ex_name` ASC),
  INDEX `fk_ksinfo_has_zhiwei_ksinfo1_idx` (`ksinfo_ks_idcard` ASC),
  CONSTRAINT `fk_ksinfo_has_zhiwei_ksinfo1`
    FOREIGN KEY (`ksinfo_ks_idcard`)
    REFERENCES `mydb`.`ksinfo` (`ks_idcard`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ksinfo_has_zhiwei_zhiwei1`
    FOREIGN KEY (`zhiwei_zw_code` , `dw_id` , `ex_name`)
    REFERENCES `mydb`.`zhiwei` (`zw_code` , `zhaokaodanwei_dw_id` , `zhaokaodanwei_exam_ex_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE `mydb`.`status` (
    `ex_name` VARCHAR(40) ,
    `kemu` INT NULL,
    `ksinfo` INT NULL,
    `kaodian` INT NULL,
    `kaochang` INT NULL,
    FOREIGN KEY (`ex_name`)
    REFERENCES `mydb`.`exam` (`ex_name`)
    ON DELETE cascade
    ON UPDATE cascade,
PRIMARY KEY (`ex_name`));

-- -----------------------------------------------------
-- Table `mydb`.`kszkz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`kszkz` (
    `ks_idcard` CHAR(18) NOT NULL,
    `ex_name` VARCHAR(45) NOT NULL,
    `zkznum` BIGINT NULL,
    PRIMARY KEY (`ks_idcard`, `ex_name`),
    INDEX `fk_ksinfo_has_exam_exam1_idx` (`ex_name` ASC),
    INDEX `fk_ksinfo_has_exam_ksinfo1_idx` (`ks_idcard` ASC),
    CONSTRAINT `fk_ksinfo_has_exam_ksinfo1`
    FOREIGN KEY (`ks_idcard`)
    REFERENCES `mydb`.`ksinfo` (`ks_idcard`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_ksinfo_has_exam_exam1`
    FOREIGN KEY (`ex_name`)
    REFERENCES `mydb`.`exam` (`ex_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


    SET SQL_MODE=@OLD_SQL_MODE;
    SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
    SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
